import { z } from 'zod';

export enum SUPPORTED_CHAINS {
  ETHEREUM = '1',
  ETHEREUM_SEPOLIA = '11155111',
  POLYGON = '137',
  POLYGON_AMOY = '2002',
  SOLANA = '1399811149',
  TRON = '728126428',
  COSMOS = '0',
}

export const ChainIdSchema = z.enum([
  SUPPORTED_CHAINS.ETHEREUM,
  SUPPORTED_CHAINS.ETHEREUM_SEPOLIA,
  SUPPORTED_CHAINS.POLYGON,
  SUPPORTED_CHAINS.POLYGON_AMOY,
  SUPPORTED_CHAINS.SOLANA,
  SUPPORTED_CHAINS.TRON,
  SUPPORTED_CHAINS.COSMOS,
]);
