name: My code passes all tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20.11.0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test Package
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: mskelton/setup-yarn@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn

      - name: Build Package
        run: yarn build

      - name: Unit Tests
        run: yarn test
